obj-$(CONFIG_MFD_NVEC)		+= nvec.o
obj-$(CONFIG_NVEC_EVENTS)	+= nvec_events.o
obj-$(CONFIG_SERIO_NVEC_PS2)	+= nvec_ps2.o
obj-$(CONFIG_NVEC_POWER) 	+= nvec_power.o
obj-$(CONFIG_KEYBOARD_NVEC) 	+= nvec_kbd.o
obj-$(CONFIG_NVEC_PAZ00) 	+= nvec_paz00.o
