#!/bin/bash

tail -n +5 < Next/Trees | while read tree type url; do
	repository=${url%#*}
	branch=${url#*#}

	if test "x$type" != "xgit"; then
		echo "Don't know how to handle type $type trees, skipping..."
		continue
	fi

	git remote set-url ${tree} ${repository}

	echo "Fetching tree $tree ($repository)..."
	git fetch $tree
done
